"""initial schema

Revision ID: da04fabf6fca
Revises: 5ac346b334f5
Create Date: 2025-10-11 02:20:21.759657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da04fabf6fca'
down_revision: Union[str, Sequence[str], None] = '5ac346b334f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('internships', sa.Column('posted_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'internships', 'users', ['posted_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'internships', type_='foreignkey')
    op.drop_column('internships', 'posted_by')
    # ### end Alembic commands ###
